//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoHarce.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoHarce.CrossCutting.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ©2016 Deloitte S.L. todos los derechos reservados..
        /// </summary>
        public static string AppFooterCopyright {
            get {
                return ResourceManager.GetString("AppFooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escritor español.
        /// </summary>
        public static string AppInfoWriter {
            get {
                return ResourceManager.GetString("AppInfoWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoría.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARCE.
        /// </summary>
        public static string AppNameDescription {
            get {
                return ResourceManager.GetString("AppNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltasar Gracián (1601-1658).
        /// </summary>
        public static string AppNameWriter {
            get {
                return ResourceManager.GetString("AppNameWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Para prevenidos no hay acasos&quot;.
        /// </summary>
        public static string AppPhrase {
            get {
                return ResourceManager.GetString("AppPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalúa todas las posibilidades.
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso a la aplicación.
        /// </summary>
        public static string CommentsLogToAccessApplication {
            get {
                return ResourceManager.GetString("CommentsLogToAccessApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeloittePdf {
            get {
                object obj = ResourceManager.GetObject("DeloittePdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla AngularJs.
        /// </summary>
        public static string Examples_MailApplicationName {
            get {
                return ResourceManager.GetString("Examples_MailApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba de correo.
        /// </summary>
        public static string Examples_MailBody {
            get {
                return ResourceManager.GetString("Examples_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lhorcajada@gmail.com.
        /// </summary>
        public static string Examples_MailFrom {
            get {
                return ResourceManager.GetString("Examples_MailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba de correo.
        /// </summary>
        public static string Examples_MailSubject {
            get {
                return ResourceManager.GetString("Examples_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lhorcajada@gmail.com.
        /// </summary>
        public static string Examples_MailTo {
            get {
                return ResourceManager.GetString("Examples_MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgAppHome {
            get {
                object obj = ResourceManager.GetObject("imgAppHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logoDeloitte {
            get {
                object obj = ResourceManager.GetObject("logoDeloitte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No autorizado.
        /// </summary>
        public static string NoAuthorized {
            get {
                return ResourceManager.GetString("NoAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El título ya existe.
        /// </summary>
        public static string TitleRepeat {
            get {
                return ResourceManager.GetString("TitleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El título es requerido.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES MAD PMS IT Desarr Externos.
        /// </summary>
        public static string UsersADGroup {
            get {
                return ResourceManager.GetString("UsersADGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Verdana {
            get {
                object obj = ResourceManager.GetObject("Verdana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lhorcajada.
        /// </summary>
        public static string WindowsAccountNameTest {
            get {
                return ResourceManager.GetString("WindowsAccountNameTest", resourceCulture);
            }
        }
    }
}
